#!/bin/bash
i=0
BASE="http://fdch.github.io"
REPO=$(basename `git rev-parse --show-toplevel`)
DATE=$(date +"%D %T")
COMMIT="updates"

while [ $i -lt 80 ]
do
	echo -ne "$(tput setaf 2)="
	i=$[$i+1]
done

echo "$(tput sgr 0)"

git add .

if [[ $1 ]] 
then
	COMMIT = "$1"
fi

git commit -m "$COMMIT"

echo "$(tput setaf 2)

Committed $COMMIT to $REPO on $DATE $(tput sgr 0)"

git push

while [ $i -gt 0 ]
do
	sleep 0.1
	echo -ne "="
	i=$[$i-1]
done

open "$BASE/$REPO"

exit