#!/bin/bash
if [[ $1 ]]
then
	cp $1 tmp
	BEGINPOINT=$(grep -nr "Quotes" tmp  | cut -d : -f 2)
	BEGINPOINT=$(echo $BEGINPOINT | cut -d ' ' -f 1)
	((BEGINPOINT=$BEGINPOINT+1))
	tail -n +$BEGINPOINT tmp > tmpcut
	ENDPOINT=$(grep -nr "Bibliography" tmpcut | cut -d : -f 2)
	((ENDPOINT=$ENDPOINT-1))
	split -l $ENDPOINT tmpcut
	grep -o -E '\w+' xaa  | tr ' ' '\n' | sort | uniq -c | awk '{print $1"\t"$2}' | sort -g -r -o $1-freq
	rm tmp*
	rm x*
else
	echo "No text specified"
fi
exit